services:
  - type: web
    name: nba-app-backend
    env: python
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn nba_backend:app --bind 0.0.0.0:$PORT
    autoDeploy: true
